openapi: 3.0.0

info:
  title: SCS User Authentication
  description: |
    [docs](https://github.com/south-coast-science/docs/wiki) > 
    [APIs](https://south-coast-science.github.io/scs-api-docs/)
    ***
    
    ### Login and Cognito account management. 
      
    Authentication requires the token name Authorization with the value `@southcoastscience.com`
    
    In the case of login, if authentication is successful, the endpoint responds with an IdToken. The IdToken should be used as the API key for subsequent requests to SCS APIs.
  version: 2.0.0

servers:
  - url: https://api.southcoastscience.com
    description: Live server

paths:
  /CogSecAPI/CognitoLogin/user:
    post:
      tags:
        - Cognito login
      summary: Present an email address and password, and receive an IdToken if successful.
      description: The request must be authorized with the header field name Authorization and value @southcoastscience.com

      security:
        - LoginAuthorization: []

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginCredentials'
            examples:
              Success:
                value:
                  email: demo@southcoastscience.com
                  password: Science123!
              InvalidCredentials:
                value:
                  email: demo@southcoastscience.com
                  password: Science
        required: true

      responses:
        '200':
          description: Present credentials and receive authentication token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /CogUsrPwdAPI/CognitoUserPassword/send-email:
    post:
      tags:
        - Cognito email
      summary: Present email address. The appropriate access email is sent to the recipient.
      description: The request must be authorized with the header field name Authorization and value @southcoastscience.com

      security:
        - LoginAuthorization: []

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailSendRequest'
        required: true

      responses:
        '200':
          description: The appropriate access email is sent to the recipient.

        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    LoginCredentials:
      description: An email address and password
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      description: Authentication status, including the session IdToken if authenticated
      type: object
      properties:
        authentication-status:
          description: Authentication status
          type: string
          enum:
            - Ok
            - InvalidCredentials
        content:
          type: object
          properties:
            AuthenticationResult:
              type: object
              properties:
                IdToken:
                  description: Token for subsequent requests
                  type: string

    EmailSendRequest:
      description: An email address
      type: object
      properties:
        email:
          type: string

    Error:
      description: A representation of an HTTP error
      type: object
      properties:
        message:
          type: string
          description: A human-readable error message

  securitySchemes:
    LoginAuthorization:
      description: The token `@southcoastscience.com`
      type: apiKey
      in: header
      name: Authorization

security:
  - LoginAuthorization: []
